package features;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMiiLE
 */
import features.operations.Deposit;
import features.operations.Tranfer;
import features.operations.Withdraw;
import features.CreateAccount;
import features.statement;
import javafx.scene.paint.Color;

public class BankMaker extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public BankMaker() {
        initComponents();
        setResizable(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Dep = new javax.swing.JButton();
        Withdraw = new javax.swing.JButton();
        Tranfer = new javax.swing.JButton();
        Interest = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Open Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 127, -1));

        Dep.setText("Deposit");
        Dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepActionPerformed(evt);
            }
        });
        getContentPane().add(Dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 127, -1));

        Withdraw.setText("Withdraw");
        Withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawActionPerformed(evt);
            }
        });
        getContentPane().add(Withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 127, -1));

        Tranfer.setText("Tranfer");
        Tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranferActionPerformed(evt);
            }
        });
        getContentPane().add(Tranfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 127, -1));

        Interest.setText("Interest Calculation");
        Interest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterestActionPerformed(evt);
            }
        });
        getContentPane().add(Interest, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jButton6.setText("Transaction printout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simplicity Banking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, 20));

        jPanel1.setBackground(new java.awt.Color(0, 0, 86));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CreateAccount frame2 = new CreateAccount();
        frame2.setVisible(true); //go to CheckIn frame
        setVisible(false);
    }                                        

    private void DepActionPerformed(java.awt.event.ActionEvent evt) {                                    
        Deposit frame2 = new Deposit();  
        frame2.setVisible(true); //go to CheckIn frame
        setVisible(false);
    }                                   

    private void WithdrawActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Withdraw frame2 = new Withdraw();
        frame2.setVisible(true); //go to CheckIn frame
        setVisible(false);
    }                                        

    private void TranferActionPerformed(java.awt.event.ActionEvent evt) {                                        
        Tranfer frame2 = new Tranfer();    
        frame2.setVisible(true); //go to CheckIn frame
        setVisible(false);
    }                                       

    private void InterestActionPerformed(java.awt.event.ActionEvent evt) {                                         
        InterestCal frame2 = new InterestCal();
        frame2.setVisible(true); //go to CheckIn frame
        setVisible(false);
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) { 
        statement frame2 = new statement();
        frame2.setSize(420, 325);
        frame2.setVisible(true); //go to CheckIn frame
        setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        BankMaker frame1 = new BankMaker();
        frame1.setBackground(java.awt.Color.yellow);
        frame1.setSize(420, 400);
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankMaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Dep;
    private javax.swing.JButton Interest;
    private javax.swing.JButton Tranfer;
    private javax.swing.JButton Withdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
